### ISSUE TITLE
Copyright information - should this possibly be more specific? Pointer to original kexpr?

### ISSUE THREAD

**Issue by smoe** [brentp/kexpr-nim#2]
Hello,

Everything builds and tests nicely. So you are providing a complete package, i.e. are including what you wrapped.
You are wrapping something that I had expected to find somewhere on
https://github.com/lh3
together with the original license - but I failed. So, is it all yours since you reimplemented it? But why then say you wrapped someone else's work? Please kindly help your README.md / LICENSE file to clear this up and/or add a short header in kexpr/*.[ch].

Many thanks
Steffen

**Comment by smoe** [comment]
Hm. It likely is https://github.com/lh3/bgt/blob/master/LICENSE.txt (MIT again, thanks go to Nilesh for spotting that) but a quick confirmation would be nice.

**Comment by brentp** [comment]
Hi Steffen, it's from here: https://github.com/attractivechaos/klib
do you want to open a pull-request with your suggested changes?

**Comment by smoe** [comment]
>  do you want to open a pull-request with your suggested changes?

https://github.com/brentp/kexpr-nim/pull/3
